apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - config/openshift/agent-policy-configmap.yaml
  - config/openshift/app-configmap.yaml
  - config/openshift/secrets.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/route.yaml
  - manifests/hpa.yaml
  - manifests/network-policy.yaml
