apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anytype-agent
  namespace: anytype
  labels:
    app.kubernetes.io/name: anytype-agent
    app.kubernetes.io/component: api
spec:
  to:
    kind: Service
    name: anytype-agent
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
